---
title: "aggregate"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

`aggregate` is a sub-meetup of the Portland R Meetup group.

These meetups are a smaller group of people, usually a dozen or so people.

It’s a more intimate group, ideal for actually meeting people, getting help with your code, sharing stories, and networking.


### Upcoming


### Past

*   2020-06-25 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/271212559/)
*   2020-04-22 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/269998352/)
*   2020-02-05 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/268099898/)
*   2019-11-21 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/266245209/)
*   2019-08-20 - [aggregate: + cRaggy](https://www.meetup.com/portland-r-user-group/events/263808712/)
*   2019-07-18 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/262851544/)
*   2019-06-18 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/261820510/)
*   2019-05-14 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/260873669/)
*   2019-04-23 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/260435394/)
*   2019-03-20 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/258545960/)
*   2019-02-19 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/258545861/)
*   2019-01-16 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/256443624/)
*   2018-12-11 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/256443624/)
*   2018-11-14 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/255779568/)
*   2018-10-16 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/253818426/)
*   2018-01-23 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/245709001/)
*   2017-12-19 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/245289388/)
*   2017-11-07 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/244320932/)
*   2017-09-18 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/242827377/)
*   2017-08-16 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/241883694/)
*   2017-07-19 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/240995059/)
*   2017-06-15 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/240454471/)
*   2017-04-19 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/238569772/)
*   2017-02-22 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/236220667/)
*   2017-01-18 - [aggregate: meet, greet, learn, collaborate](https://www.meetup.com/portland-r-user-group/events/236220667/)
*   2016-11-10 - [aggregate: meet, greet, learn, collaborate](http://www.meetup.com/portland-r-user-group/events/235130167/)
*   2016-10-18 - [aggregate: meet, greet, learn, collaborate](http://www.meetup.com/portland-r-user-group/events/234177763/)
*   2016-08-24 - [aggregate: meet, greet, learn, collaborate](http://www.meetup.com/portland-r-user-group/events/233121100/)
*   2016-08-02 - [aggregate: meet, greet, learn, collaborate](http://www.meetup.com/portland-r-user-group/events/232134520/)
*   2016-06-22 - [aggregate: meet, greet, learn, collaborate](http://www.meetup.com/portland-r-user-group/events/231720260/)
*   2016-05-31 - [aggregate: meet, greet, learn, collaborate](http://www.meetup.com/portland-r-user-group/events/231057729/)
*   2016-05-10 - [Meet, Greet, Hack - Our 1st shot at this, Join Us!](http://www.meetup.com/portland-r-user-group/events/230627770/)
