---
title: "PDX R Code of Conduct"
description: |
  Code of Conduct for PDX R User Group.
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

PDX R Meetup is dedicated to providing a harassment-free meetup experience for everyone regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion. We do not tolerate harassment of meetup participants in any form. Sexual language and imagery is not appropriate for any meetup venue, including talks. PDX R meetup participants violating these rules may be sanctioned or expelled from meetup events at the discretion of the meetup organizers.

Harassment includes verbal comments that reinforce social structures of domination related to gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, religion; sexual images in public spaces; deliberate intimidation; stalking; following; harassing photography or recording; sustained disruption of talks or other events; inappropriate physical contact; and unwelcome sexual attention. Participants asked to stop any harassing behavior are expected to comply immediately.

If a participant engages in harassing behavior, the meetup organizers may take any action they deem appropriate, including warning the offender or expulsion from the meetup with no refund. If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of the meetup organizers immediately:

Ted Laderas (tedladeras@gmail.com, 503-481-8470)
Marley Buchman (michaelmbuchman@gmail.com, 503-577-4985)