---
title: "Portland R User Group"
description: |
  Welcome to the Portland R User Group! We're a group
  learning how to work in R. All levels are welcome!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

We are the R user group for Portland, Oregon. R is a free software environment for statistical computing and graphics. Our goal is to support and share R experience and knowledge among its users in the Portland community.

We have regularly scheduled monthly meetups ([aggregate](aggregate.html)) and also host [other events](meetups.html).

Follow news about the group on Twitter at [\@pdxrlang](https://twitter.com/pdxrlang)

# Join the PDX Data Slack

Join other pdxrlang’ers and other portland area data science folks at the PDX slack: 

[pdxdata.slack.com](https://pdxdata.slack.com)  

You can Invite yourself [here](https://join.slack.com/t/pdxdata/shared_invite/zt-4yxw4ic6-3OWOKkidrTeGkNgra5vdCw).

# Upcoming Events

- November 17 - Kelly O'Briant - Introduction to RStudio Connect 
- December 8 - aggregate - featuring Advanced RMarkdown tips by Brendan Cullen

# Want to give a talk?

We always want people to share their R knowledge. You can give a short lightning style talk as part of aggregate, or a longer form talk about an R Topic as a meetup session. Get in touch via email at pdxrlang@gmail.com, or if you’re a Meetup.com member you can message us there.

# Acknowledgements

PDX R User Group is partially funded by a grant from R Consortium.